[attackgraph_memory]
is_custom = 1
label = Add to AttackGraph Memory
description = Pushes the alert entities (Users, IPs) into the in-memory NetworkX Attack Graph.
icon_path = appIcon.png
payload_format = json
python.version = python3
