#
# Splunk app configuration file
#

[install]
is_configured = 1
install_source_checksum = 4d263f076e2ee4100cd38ddb89d925ce7ba22ae4

[ui]
is_visible = true
label = SplunkAgent

[launcher]
author = samyak
description = Connects your local Splunk to Neo4j.
version = 1.0.1
